-- ====================================================================
-- StudyVerse Supabase Database Seed Data
-- Full Relational Seed matching JS Data Exactly
-- ====================================================================

-- 1. Insert Categories
insert into public.categories (id, name, code, description, color) values
('cat-core', 'Professional Core', 'PCC', 'Foundational computer engineering and system architecture courses.', '#3b82f6'),
('cat-bs', 'Basic Science', 'BSC', 'Mathematics, physics, and computational statistics fundamentals.', '#06b6d4'),
('cat-es', 'Engineering Science', 'ESC', 'Core engineering concepts across electronics, electrical, and mechanics.', '#10b981'),
('cat-elec', 'Professional Elective', 'PEC', 'Specialized domain courses spanning AI, Cloud, Security, and Big Data.', '#8b5cf6'),
('cat-hss', 'Humanities & Social Sciences', 'HSMC', 'Professional communication, economics, and engineering ethics.', '#f59e0b'),
('cat-proj', 'Project & Internship', 'PROJ', 'Practical capstone engineering projects and industrial training.', '#ec4899')
on conflict (id) do nothing;

-- 2. Insert Semesters
insert into public.semesters (id, number, roman, title, subtitle, tagline, color, glow, orbit_radius, orbit_speed, planet_size, description, subject_count, credits, highlights) values
(1, 1, 'I', 'Semester 1', 'Foundation & Basic Engineering', 'Initial orbit around fundamental physical and computational principles', '#06b6d4', 'rgba(6, 182, 212, 0.4)', 2.2, 0.8, 0.28, 'Establish foundational principles in differential calculus, physics, and initial imperative C programming.', 6, 20, ARRAY['Calculus & Linear Algebra', 'C Programming Fundamentals', 'Basic Electrical Systems']),
(2, 2, 'II', 'Semester 2', 'Core Sciences & Technical Communication', 'Expanding trajectory through electronics and advanced scientific methods', '#0ea5e9', 'rgba(14, 165, 233, 0.4)', 3.1, 0.65, 0.32, 'Deepen mathematical analysis with vector calculus and master semiconductor devices and workshop fabrication.', 6, 21, ARRAY['Vector Calculus & ODEs', 'Semiconductor Electronics', 'Technical English']),
(3, 3, 'III', 'Semester 3', 'Data Structures & Architecture Genesis', 'Entering computational core territory with linear data structures & relational schemas', '#6366f1', 'rgba(99, 102, 241, 0.4)', 4.0, 0.52, 0.35, 'Transition into essential computer science foundations: data structures, relational DBMS, and OOP with C++.', 6, 22, ARRAY['Data Structures & Algorithms', 'Database Systems (SQL)', 'Object Oriented C++']),
(4, 4, 'IV', 'Semester 4', 'Operating Systems & Algorithm Design', 'System-level orbit intersecting kernel architecture and discrete proofs', '#8b5cf6', 'rgba(139, 92, 246, 0.4)', 4.9, 0.44, 0.38, 'Tackle the bedrock of systems engineering: kernel process scheduling, memory hierarchies, and algorithm complexity.', 6, 23, ARRAY['OS Kernels & Concurrency', 'Design & Analysis of Algorithms', 'Computer Architecture']),
(5, 5, 'V', 'Semester 5', 'Networks & Computational Theory', 'High-speed packet transport and theoretical automata mechanics', '#d946ef', 'rgba(217, 70, 239, 0.4)', 5.8, 0.36, 0.36, 'Understand the global Internet routing stack, formal Turing machines, and enterprise software engineering patterns.', 6, 22, ARRAY['TCP/IP Network Stack', 'Theory of Computation', 'Modern Software Engineering']),
(6, 6, 'VI', 'Semester 6', 'Artificial Intelligence & Compilers', 'Deepening intelligence nodes, lexical parsing, and defensive cryptography', '#f43f5e', 'rgba(244, 63, 94, 0.4)', 6.7, 0.30, 0.34, 'Construct language compilers, implement heuristic search agents, and secure systems using modern cryptography.', 6, 22, ARRAY['AI Heuristics & Search', 'Lexical & Syntax Parsing', 'Cryptography & Network Security']),
(7, 7, 'VII', 'Semester 7', 'Cloud Platforms & Machine Learning', 'Distributed planetary clusters and predictive neural feature engines', '#f59e0b', 'rgba(245, 158, 11, 0.4)', 7.6, 0.24, 0.36, 'Deploy cloud architectures, train statistical machine learning pipelines, and begin industry Capstone Project Phase 1.', 6, 21, ARRAY['Machine Learning Models', 'Cloud Microservices', 'Big Data Hadoop/Spark']),
(8, 8, 'VIII', 'Semester 8', 'Deep Learning & Industry Capstone', 'Final orbit: transformer architectures, blockchain consensus, and full deployment', '#10b981', 'rgba(16, 185, 129, 0.4)', 8.5, 0.18, 0.40, 'Master advanced deep neural networks, decentralized blockchain protocols, and deliver enterprise-grade Capstone projects.', 6, 18, ARRAY['Deep Neural Networks', 'Blockchain Consensus', 'Major Industrial Internship'])
on conflict (id) do nothing;

-- 3. Insert All 48 Subjects
insert into public.subjects (id, code, name, short_name, semester_id, category_id, credits, description, important_topics, related_subject_ids) values
-- Semester 1
('sub-3110014', '3110014', 'Mathematics - I', 'Maths-1', 1, 'cat-bs', 4, 'Differential calculus, indeterminate forms, improper integrals, matrices, rank of matrix, and eigenvalues.', ARRAY['Rolle’s Theorem', 'Eigenvalues and Eigenvectors', 'Fourier Series'], ARRAY['sub-3110015']),
('sub-3110018', '3110018', 'Physics', 'Physics', 1, 'cat-bs', 4, 'Optics, interference, diffraction, lasers, fiber optics, quantum mechanics, and magnetic materials.', ARRAY['Newton’s rings', 'He-Ne Lasers', 'Numerical aperture'], ARRAY['sub-3110016']),
('sub-3110005', '3110005', 'Basic Electrical Engineering', 'BEE', 1, 'cat-es', 4, 'DC circuits analysis, AC circuits, magnetic circuits, single-phase transformers, and electrical safety.', ARRAY['Thevenin & Norton', 'RLC Resonance', 'Transformers'], ARRAY['sub-3110016']),
('sub-3110003', '3110003', 'Programming for Problem Solving', 'PPS', 1, 'cat-es', 4, 'Foundational programming in C: control structures, arrays, pointers, functions, structures, and file I/O.', ARRAY['Pointers', 'Dynamic memory allocation', 'Recursion'], ARRAY['sub-3130702']),
('sub-3110013', '3110013', 'Engineering Graphics & Design', 'EGD', 1, 'cat-es', 3, 'Engineering curves, projection of points, lines, planes, solids, section of solids, isometric drawings, and CAD.', ARRAY['Conic sections', 'Projections of solids', 'Isometric view'], ARRAY['sub-3110006']),
('sub-3110007', '3110007', 'Environmental Science', 'ES', 1, 'cat-hss', 2, 'Ecology, ecosystems, renewable and non-renewable energy, environmental pollution, solid waste, and green engineering.', ARRAY['Ecosystem cycles', 'Air & water pollution', 'Renewable energy'], ARRAY['sub-3140709']),

-- Semester 2
('sub-3110015', '3110015', 'Mathematics - II', 'Maths-2', 2, 'cat-bs', 4, 'Vector calculus, gradient, divergence, curl, multiple integrals, Green and Stokes theorems, first and higher order ODEs.', ARRAY['Directional derivative', 'Green & Stokes theorems', 'Higher order ODEs'], ARRAY['sub-3110014']),
('sub-3110006', '3110006', 'Basic Mechanical Engineering', 'BME', 2, 'cat-es', 4, 'Thermodynamics laws, steam generation, internal combustion engines, pumps, compressors, and power transmission.', ARRAY['Laws of thermodynamics', 'Otto & Diesel cycles', 'Centrifugal pumps'], ARRAY['sub-3110013']),
('sub-3110016', '3110016', 'Basic Electronics', 'BE', 2, 'cat-es', 4, 'Semiconductor diodes, rectifiers, BJT biasing and configurations, operational amplifiers, and boolean logic gates.', ARRAY['Zener diode', 'BJT characteristics', 'Op-Amp 741'], ARRAY['sub-3130704']),
('sub-3110002', '3110002', 'English for Communication', 'English', 2, 'cat-hss', 2, 'Vocabulary enrichment, technical reporting, formal business correspondence, presentation skills, and phonetics.', ARRAY['Technical report writing', 'Resume writing', 'Presentation skills'], ARRAY['sub-3130004']),
('sub-3110012', '3110012', 'Workshop / Manufacturing Practices', 'WMP', 2, 'cat-es', 3, 'Fitting shop, carpentry, tin smithy, arc and gas welding, machining operations, and safety standards.', ARRAY['Carpentry joints', 'Arc welding', 'Lathe machine operations'], ARRAY['sub-3110013']),
('sub-3110001', '3110001', 'Applied Chemistry', 'Chem', 2, 'cat-bs', 4, 'Water technology, polymers, fuels, combustion, corrosion mechanisms, and nanomaterials for engineering.', ARRAY['Water hardness EDTA', 'Polymer synthesis', 'Corrosion protection'], ARRAY['sub-3110007']),

-- Semester 3
('sub-3130006', '3130006', 'Probability and Statistics', 'P&S', 3, 'cat-bs', 4, 'Random variables, probability distributions, sampling theory, hypothesis testing, ANOVA, and linear regression.', ARRAY['Bayes theorem', 'Normal distribution', 'Hypothesis t-test'], ARRAY['sub-3140708']),
('sub-3130702', '3130702', 'Data Structures', 'DS', 3, 'cat-core', 4, 'Arrays, stacks, queues, linked lists, binary trees, AVL trees, graphs, sorting, searching, and hashing algorithms.', ARRAY['Infix to Postfix', 'Binary Search Trees', 'AVL Rotations', 'Dijkstra and BFS'], ARRAY['sub-3110003', 'sub-3140701']),
('sub-3130704', '3130704', 'Digital Electronics & Logic Design', 'DELD', 3, 'cat-core', 4, 'K-map minimization, combinational circuits, multiplexers, sequential circuits, flip-flops, registers, and counters.', ARRAY['K-Map 4 variables', 'Adders & Subtractors', 'JK Flip-Flop excitation', 'Counters'], ARRAY['sub-3110016', 'sub-3140707']),
('sub-3130703', '3130703', 'Database Management Systems', 'DBMS', 3, 'cat-core', 4, 'ER modeling, relational algebra, SQL DDL/DML, normalization (1NF to BCNF), transaction ACID properties, and indexing.', ARRAY['ER to Relational', 'SQL Complex Joins', 'BCNF Decomposition', 'ACID & 2PL'], ARRAY['sub-3130702', 'sub-3150709']),
('sub-3130705', '3130705', 'Object Oriented Programming with C++', 'OOP-C++', 3, 'cat-core', 4, 'Classes, objects, constructors, destructors, operator overloading, inheritance, virtual functions, and templates.', ARRAY['Virtual Functions', 'Operator Overloading', 'Templates & STL'], ARRAY['sub-3110003', 'sub-3150703']),
('sub-3130004', '3130004', 'Effective Technical Communication', 'ETC', 3, 'cat-hss', 2, 'Technical proposals, project presentations, interpersonal dynamics, business ethics, and corporate negotiations.', ARRAY['Technical proposal drafting', 'Group discussions', 'Negotiation dynamics'], ARRAY['sub-3110002']),

-- Semester 4
('sub-3140708', '3140708', 'Discrete Mathematics & Graph Theory', 'DMGT', 4, 'cat-bs', 4, 'Propositional logic, set relations, lattice theory, algebraic structures, groups, planar graphs, and graph coloring.', ARRAY['Truth tables', 'Hasse Diagrams', 'Group Theory', 'Eulerian & Hamiltonian'], ARRAY['sub-3130006', 'sub-3140701']),
('sub-3140702', '3140702', 'Operating System', 'OS', 4, 'cat-core', 4, 'Process management, CPU scheduling, semaphores, deadlock detection/avoidance, virtual memory paging, and file systems.', ARRAY['Process Synchronization', 'Banker’s Algorithm', 'Page Replacement FIFO/LRU', 'Disk Scheduling'], ARRAY['sub-3130702', 'sub-3140707']),
('sub-3140707', '3140707', 'Computer Organization & Architecture', 'COA', 4, 'cat-core', 4, 'Instruction sets, addressing modes, ALU design, Booth multiplication, pipeline hazards, cache mapping, and interrupt I/O.', ARRAY['Booth Multiplication', 'Pipelining Hazards', 'Cache Associative Mapping'], ARRAY['sub-3130704', 'sub-3140702']),
('sub-3140709', '3140709', 'Principles of Economics & Management', 'PEM', 4, 'cat-hss', 3, 'Demand and supply elasticity, cost analysis, market structures, break-even analysis, financial statements, and planning.', ARRAY['Elasticity of Demand', 'Break-Even Analysis', 'Balance Sheet Analysis'], ARRAY['sub-3110007']),
('sub-3140701', '3140701', 'Design and Analysis of Algorithms', 'DAA', 4, 'cat-core', 4, 'Asymptotic notations, divide and conquer, greedy methods, dynamic programming, backtracking, branch & bound, and NP-completeness.', ARRAY['Master Theorem', '0/1 Knapsack DP', 'N-Queens Backtracking', 'NP-Completeness'], ARRAY['sub-3130702', 'sub-3150711']),
('sub-3140705', '3140705', 'Python Programming', 'Python', 4, 'cat-core', 4, 'Data structures, list comprehensions, lambda functions, OOP in Python, file operations, NumPy, Pandas, and regular expressions.', ARRAY['List Comprehensions', 'NumPy & Pandas', 'OOP in Python'], ARRAY['sub-3110003', 'sub-3160714']),

-- Semester 5
('sub-3150710', '3150710', 'Computer Networks', 'CN', 5, 'cat-core', 4, 'OSI and TCP/IP models, framing, flow control, subnetting, IPv4/IPv6, routing protocols (OSPF, BGP), and TCP flow/congestion.', ARRAY['Subnetting & CIDR', 'CRC & Sliding Window', 'TCP Congestion Control', 'DNS & HTTP'], ARRAY['sub-3140702', 'sub-3160716']),
('sub-3150711', '3150711', 'Theory of Computation', 'TOC', 5, 'cat-core', 4, 'Deterministic and NFA, regular expressions, pumping lemma, context-free grammars, pushdown automata, and Turing machines.', ARRAY['NFA to DFA', 'Pumping Lemma', 'Pushdown Automata', 'Turing Machines'], ARRAY['sub-3140708', 'sub-3140701']),
('sub-3150709', '3150709', 'Software Engineering', 'SE', 5, 'cat-core', 4, 'Software process models, Agile Scrum, SRS documentation, UML design, architectural patterns, black/white box testing, and maintenance.', ARRAY['Agile Scrum', 'SRS IEEE Format', 'Cyclomatic Complexity', 'Testing Techniques'], ARRAY['sub-3130703', 'sub-3160713']),
('sub-3150703', '3150703', 'Advanced Java Programming', 'Adv-Java', 5, 'cat-elec', 4, 'JDBC, servlets, JSP, JavaBeans, Spring core fundamentals, Hibernate ORM, and RESTful web service integrations.', ARRAY['JDBC PreparedStatement', 'Servlet Session Tracking', 'Spring Core IoC'], ARRAY['sub-3130705', 'sub-3160713']),
('sub-3150713', '3150713', 'Cyber Security & Laws', 'CSL', 5, 'cat-core', 3, 'Vulnerabilities, malware taxonomy, OWASP Top 10, penetration testing, digital forensics, and Indian IT Act 2000.', ARRAY['OWASP Top 10', 'SQL Injection & XSS', 'IT Act 2000'], ARRAY['sub-3150710', 'sub-3160716']),
('sub-3150005', '3150005', 'Professional Ethics & Values', 'PEV', 5, 'cat-hss', 2, 'Human values, moral dilemmas, codes of ethics (IEEE/ACM), engineering responsibility, whistleblower protection, and safety.', ARRAY['IEEE Codes of Ethics', 'Whistleblower protection', 'Intellectual Property'], ARRAY['sub-3110007', 'sub-3140709']),

-- Semester 6
('sub-3160714', '3160714', 'Artificial Intelligence', 'AI', 6, 'cat-core', 4, 'State space search, heuristics, A* algorithm, game playing (Minimax, Alpha-Beta pruning), knowledge representation, and expert systems.', ARRAY['A* Heuristic Search', 'Minimax & Alpha-Beta', 'First Order Logic', 'Bayesian Networks'], ARRAY['sub-3140701', 'sub-3170716']),
('sub-3160713', '3160713', 'Web Technology & Full-Stack', 'WebTech', 6, 'cat-core', 4, 'HTML5 semantic standards, CSS3 flexbox/grid, JavaScript ES6+, DOM APIs, Node.js, Express, MongoDB, and modern React concepts.', ARRAY['JavaScript ES6+ Async', 'Node & Express REST', 'MongoDB NoSQL', 'React Hooks'], ARRAY['sub-3130703', 'sub-3150709']),
('sub-3160707', '3160707', 'Advanced Algorithm Design', 'AAD', 6, 'cat-elec', 4, 'Amortized analysis, binomial heaps, Fibonacci heaps, randomized algorithms, string matching (KMP, Rabin-Karp), and network flows.', ARRAY['Amortized Potential Method', 'Fibonacci Heaps', 'KMP String Matching', 'Ford-Fulkerson Max Flow'], ARRAY['sub-3140701']),
('sub-3160704', '3160704', 'Compiler Design', 'CD', 6, 'cat-core', 4, 'Lexical analysis, Lex/Flex, parsing techniques (LL, LR, LALR), syntax-directed translation, three-address code, and code optimization.', ARRAY['LL(1) Parse Tables', 'LALR(1) Parsing', 'Three Address Code', 'Code Optimization'], ARRAY['sub-3150711', 'sub-3140707']),
('sub-3160716', '3160716', 'Cryptography & Network Security', 'CNS', 6, 'cat-core', 4, 'Symmetric ciphers (DES, AES), asymmetric crypto (RSA, ECC), hash functions (SHA-256), digital signatures, SSL/TLS, and firewalls.', ARRAY['RSA Cryptosystem', 'AES Encryption Rounds', 'Diffie-Hellman Key Exchange', 'SSL/TLS Handshake'], ARRAY['sub-3150710', 'sub-3180702']),
('sub-3160717', '3160717', 'Internet of Things (IoT)', 'IoT', 6, 'cat-elec', 3, 'IoT architecture, embedded sensing, Arduino/Raspberry Pi, communication protocols (MQTT, CoAP), cloud platforms, and smart cities.', ARRAY['MQTT Architecture', 'Raspberry Pi GPIO', 'LoRaWAN & Zigbee'], ARRAY['sub-3110016', 'sub-3150710']),

-- Semester 7
('sub-3170716', '3170716', 'Machine Learning', 'ML', 7, 'cat-core', 4, 'Supervised learning, linear/logistic regression, decision trees, SVM, ensemble methods (Random Forest, XGBoost), and unsupervised clustering.', ARRAY['Linear & Logistic Regression', 'Support Vector Machines', 'Random Forest & Boosting', 'PCA Dimensionality'], ARRAY['sub-3130006', 'sub-3160714', 'sub-3180701']),
('sub-3170717', '3170717', 'Cloud Computing', 'Cloud', 7, 'cat-core', 4, 'NIST cloud characteristics, IaaS/PaaS/SaaS models, hypervisors, Docker containers, Kubernetes orchestration, and AWS/Azure architectures.', ARRAY['Docker Containerization', 'Kubernetes Pods & Deployments', 'IaaS vs PaaS vs SaaS', 'Hypervisors'], ARRAY['sub-3140702', 'sub-3150710', 'sub-3180704']),
('sub-3170719', '3170719', 'Big Data Analytics', 'BigData', 7, 'cat-elec', 4, 'The 5 Vs of Big Data, Hadoop Distributed File System (HDFS), MapReduce programming, Apache Spark RDDs, and NoSQL databases.', ARRAY['Hadoop HDFS Architecture', 'MapReduce Programming', 'Apache Spark RDDs', 'NoSQL Cassandra'], ARRAY['sub-3130703', 'sub-3170716']),
('sub-3170720', '3170720', 'Mobile Application Development', 'MAD', 7, 'cat-elec', 4, 'Android application architecture, activities, fragments, intents, Jetpack layouts, SQLite/Room database, and Flutter cross-platform basics.', ARRAY['Activity Lifecycle', 'RecyclerView with Adapters', 'Room Database & SQLite', 'Retrofit API Calls'], ARRAY['sub-3150703', 'sub-3160713']),
('sub-3170721', '3170721', 'Information & Retrieval Systems', 'IRS', 7, 'cat-elec', 3, 'Boolean retrieval models, vector space models, TF-IDF term weighting, inverted indexing, web crawling, and PageRank algorithms.', ARRAY['TF-IDF Weighting', 'Inverted Index Construction', 'Google PageRank Algorithm'], ARRAY['sub-3130702', 'sub-3170716']),
('sub-3170001', '3170001', 'Project Phase - I', 'Proj-1', 7, 'cat-proj', 2, 'Literature survey, problem identification, SRS documentation, system architecture design, and initial proof-of-concept prototype.', ARRAY['Literature Survey', 'System Architecture Design', 'Prototype Proof of Concept'], ARRAY['sub-3150709', 'sub-3180001']),

-- Semester 8
('sub-3180701', '3180701', 'Deep Learning & Neural Networks', 'DL', 8, 'cat-core', 4, 'Perceptrons, backpropagation, CNNs, RNNs, LSTMs, attention mechanisms, Transformer architectures, and GANs.', ARRAY['Backpropagation Gradient', 'Convolutional Neural Networks', 'LSTM Recurrent Networks', 'Self-Attention Transformers'], ARRAY['sub-3160714', 'sub-3170716', 'sub-3180703']),
('sub-3180702', '3180702', 'Blockchain Technology', 'Blockchain', 8, 'cat-elec', 4, 'Decentralized ledgers, SHA-256 proof of work, proof of stake, Ethereum smart contracts, Solidity, and decentralized apps (dApps).', ARRAY['Proof of Work vs Stake', 'Solidity Smart Contracts', 'Ethereum EVM State', 'Decentralized Apps'], ARRAY['sub-3160716', 'sub-3150713']),
('sub-3180703', '3180703', 'Natural Language Processing', 'NLP', 8, 'cat-elec', 4, 'Morphology, N-gram language models, word embeddings (Word2Vec, GloVe), seq2seq models, BERT, and generative LLMs.', ARRAY['Word2Vec Embeddings', 'N-Gram Perplexity', 'BERT & Transformer Attention'], ARRAY['sub-3170716', 'sub-3180701']),
('sub-3180704', '3180704', 'DevOps & Cloud Native Architecture', 'DevOps', 8, 'cat-elec', 3, 'CI/CD pipelines, GitOps, Infrastructure as Code (Terraform), Ansible configuration, Prometheus monitoring, and microservices.', ARRAY['GitHub Actions CI/CD', 'Terraform Declarative IaC', 'Kubernetes Helm & GitOps', 'Prometheus Monitoring'], ARRAY['sub-3150709', 'sub-3170717']),
('sub-3180705', '3180705', 'Quantum Computing Foundations', 'Quantum', 8, 'cat-elec', 3, 'Qubits, superposition, quantum entanglement, quantum gates (Hadamard, CNOT), Deutsch-Jozsa algorithm, and Shor’s algorithm.', ARRAY['Bloch Sphere & Qubits', 'Quantum Superposition', 'Hadamard & CNOT Gates', 'Shor’s Factorization'], ARRAY['sub-3110014', 'sub-3140708']),
('sub-3180001', '3180001', 'Major Project & Industry Internship', 'Capstone', 8, 'cat-proj', 6, 'Full-semester industry internship or comprehensive capstone product development, cloud deployment, and final GTU thesis defense.', ARRAY['Full-Stack Deployment', 'Automated Test Suites', 'GTU Engineering Dissertation'], ARRAY['sub-3170001', 'sub-3180704'])
on conflict (id) do nothing;

-- 4. Sample Syllabus Units for Core OS (3140702)
insert into public.syllabus_units (id, subject_id, unit_number, title, hours, weightage, topics) values
('syl-3140702-1', 'sub-3140702', 1, 'Introduction to Operating Systems & System Structures', 6, 15, ARRAY['What is an Operating System?', 'System Calls and System Programs', 'OS Structure Monolithic and Microkernel']),
('syl-3140702-2', 'sub-3140702', 2, 'Processes, Threads & CPU Scheduling', 10, 22, ARRAY['Process Control Block (PCB)', 'Context Switching', 'FCFS, SJF, Round Robin Scheduling']),
('syl-3140702-3', 'sub-3140702', 3, 'Synchronization & Deadlocks', 10, 22, ARRAY['Critical Section Problem', 'Peterson Solution', 'Semaphores', 'Bankers Algorithm']),
('syl-3140702-4', 'sub-3140702', 4, 'Memory Management & Virtual Memory', 10, 23, ARRAY['Paging and TLB', 'Demand Paging', 'Page Replacement FIFO and LRU', 'Thrashing']),
('syl-3140702-5', 'sub-3140702', 5, 'Storage Management, File Systems & I/O Systems', 8, 18, ARRAY['File Concepts and Allocation Methods', 'Disk Scheduling FCFS, SSTF, SCAN, C-SCAN', 'RAID Levels'])
on conflict (id) do nothing;

-- 5. Sample Materials
insert into public.materials (id, subject_id, semester_id, title, type, author, size, pages, downloads, rating, uploaded_date, file_url, description, tags) values
('mat-3140702-pdf-1', 'sub-3140702', 4, 'Operating System Complete Handwritten Master Notes', 'pdf', 'Prof. Dave & GTU Toppers Circle', '5.8 MB', '84 pages', 2480, 4.9, '2024-02-15', 'https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf', 'Complete chapter-wise lecture notes covering processes, synchronization, memory management, and file systems with solved GTU numericals.', ARRAY['Comprehensive', 'Exam Oriented', 'Solved Numericals']),
('mat-3140702-ppt-1', 'sub-3140702', 4, 'OS Visual Classroom Lecture Slide Deck', 'ppt', 'GTU Faculty Portal', '12.4 MB', '62 slides', 1230, 4.7, '2024-01-20', 'https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf', 'High-resolution slide presentation illustrating kernel architecture, multi-threading models, and synchronization algorithms.', ARRAY['Classroom Slides', 'Visual Diagrams', 'Quick Review']),
('mat-3140702-notes-1', 'sub-3140702', 4, 'OS Rapid One-Night Formula & Algorithm Sheet', 'notes', 'Dept. of Computer Engineering', '2.1 MB', '24 pages', 3120, 4.8, '2024-03-10', 'https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf', 'Rapid revision sheet containing all CPU scheduling, page replacement, and disk scheduling algorithms for last minute preparation.', ARRAY['Quick Revision', 'Formula Sheet', 'Last-Minute Prep'])
on conflict (id) do nothing;

-- 6. Sample Question Papers (PYQs)
insert into public.pyqs (id, subject_id, semester_id, year, season, title, paper_code, max_marks, duration, downloads, has_solution, file_url, difficulty, description) values
('pyq-3140702-2024-s', 'sub-3140702', 4, 2024, 'Summer', 'Operating System - Summer 2024 Exam Paper', '3140702-S24', 70, '2.5 Hours', 1840, true, 'https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf', 'Moderate', 'Official GTU Summer 2024 theory examination paper with complete marking scheme and step-by-step solutions.'),
('pyq-3140702-2023-w', 'sub-3140702', 4, 2023, 'Winter', 'Operating System - Winter 2023 Exam Paper', '3140702-W23', 70, '2.5 Hours', 1520, true, 'https://raw.githubusercontent.com/mozilla/pdf.js/master/examples/learning/helloworld.pdf', 'Moderate', 'Official GTU Winter 2023 regular examination paper with model answer keys.')
on conflict (id) do nothing;
